export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILTURE: "LOGIN_FAILTURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: " LOGOUT_REQUEST",
  LOGOUT_SUCCESS: " LOGOUT_SUCCESS",
  LOGOUT_FAILURE: " LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const adminConstants = {
  ADMIN_GET_EMPLOYEE_REQUEST: "ADMIN_GET_EMPLOYEE_REQUEST",
  ADMIN_GET_EMPLOYEE_SUCCESS: "ADMIN_GET_EMPLOYEE_SUCCESS",
  ADMIN_GET_EMPLOYEE_FAILURE: "ADMIN_GET_EMPLOYEE_REQUEST",
};
