export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILTURE: "LOGIN_FAILTURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: " LOGOUT_REQUEST",
  LOGOUT_SUCCESS: " LOGOUT_SUCCESS",
  LOGOUT_FAILURE: " LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  USER_VERIFY_OTP_REQUEST: "USER_VERIFY_OTP_REQUEST",
  USER_VERIFY_OTP_SUCCESS: "USER_VERIFY_OTP_SUCCESS",
  USER_VERIFY_OTP_FAILURE: "USER_VERIFY_OTP_FAILURE",

  USER_SIGNIN_REQUEST: "USER_SIGNIN_REQUEST",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAILURE: "USER_SIGNIN_REQUEST",

  USER_GET_USER_REQUEST: "USER_GET_USER_REQUEST",
  USER_GET_USER_SUCCESS: "USER_GET_USER_SUCCESS",
  USER_GET_USER_FAILURE: "USER_GET_USER_FAILURE",

  USER_SEND_MAIL_REQUEST: "USER_SEND_MAIL_REQUEST",
  USER_SEND_MAIL_SUCCESS: "USER_SEND_MAIL_SUCCESS",
  USER_SEND_MAIL_FAILURE: "USER_SEND_MAIL_FAILURE",

  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAILURE: "USER_UPDATE_FAILURE",
};

export const adminConstants = {
  ADMIN_GET_EMPLOYEE_REQUEST: "ADMIN_GET_EMPLOYEE_REQUEST",
  ADMIN_GET_EMPLOYEE_SUCCESS: "ADMIN_GET_EMPLOYEE_SUCCESS",
  ADMIN_GET_EMPLOYEE_FAILURE: "ADMIN_GET_EMPLOYEE_REQUEST",

  ADMIN_GET_EMPLOYEE_TOKEN_REQUEST: "ADMIN_GET_EMPLOYEE_TOKEN_REQUEST",
  ADMIN_GET_EMPLOYEE_TOKEN_SUCCESS: "ADMIN_GET_EMPLOYEE_TOKEN_SUCCESS",
  ADMIN_GET_EMPLOYEE_TOKEN_FAILURE: "ADMIN_GET_EMPLOYEE_TOKEN_REQUEST",

  ADMIN_GET_DEPARTMENT_REQUEST: "ADMIN_GET_DEPARTMENT_REQUEST",
  ADMIN_GET_DEPARTMENT_SUCCESS: "ADMIN_GET_DEPARTMENT_SUCCESS",
  ADMIN_GET_DEPARTMENT_FAILURE: "ADMIN_GET_DEPARTMENT_FAILURE",

  ADMIN_CREATE_EMPLOYEE_REQUEST: "ADMIN_CREATE_EMPLOYEE_REQUEST",
  ADMIN_CREATE_EMPLOYEE_SUCCESS: "ADMIN_CREATE_EMPLOYEE_SUCCESS",
  ADMIN_CREATE_EMPLOYEE_FAILURE: "ADMIN_CREATE_EMPLOYEE_FAILURE",

  ADMIN_CREATE_USER_REQUEST: "ADMIN_CREATE_USER_REQUEST",
  ADMIN_CREATE_USER_SUCCESS: "ADMIN_CREATE_USER_SUCCESS",
  ADMIN_CREATE_USER_FAILURE: "ADMIN_CREATE_USER_FAILURE",

  ADMIN_GET_USER_REQUEST: "ADMIN_GET_USER_REQUEST",
  ADMIN_GET_USER_SUCCESS: "ADMIN_GET_USER_SUCCESS",
  ADMIN_GET_USER_FAILURE: "ADMIN_GET_USER_FAILURE",

  ADMIN_GET_USER_BY_SLUG_REQUEST: "ADMIN_GET_USER_BY_SLUG_REQUEST",
  ADMIN_GET_USER_BY_SLUG_SUCCESS: "ADMIN_GET_USER_BY_SLUG_SUCCESS",
  ADMIN_GET_USER_BY_SLUG_FAILURE: "ADMIN_GET_USER_BY_SLUG_FAILURE",

  ADMIN_GET_EMPLOYEE_BY_SLUG_REQUEST: "ADMIN_GET_EMPLOYEE_BY_SLUG_REQUEST",
  ADMIN_GET_EMPLOYEE_BY_SLUG_SUCCESS: "ADMIN_GET_EMPLOYEE_BY_SLUG_SUCCESS",
  ADMIN_GET_EMPLOYEE_BY_SLUG_FAILURE: "ADMIN_GET_EMPLOYEE_BY_SLUG_FAILURE",

  ADMIN_DELETE_USER_REQUEST: "ADMIN_DELETE_USER_REQUEST",
  ADMIN_DELETE_USER_SUCCESS: "ADMIN_DELETE_USER_SUCCESS",
  ADMIN_DELETE_USER_FAILURE: "ADMIN_DELETE_USER_FAILURE",

  ADMIN_DELETE_EMPLOYEE_REQUEST: "ADMIN_DELETE_EMPLOYEE_REQUEST",
  ADMIN_DELETE_EMPLOYEE_SUCCESS: "ADMIN_DELETE_EMPLOYEE_SUCCESS",
  ADMIN_DELETE_EMPLOYEE_FAILURE: "ADMIN_DELETE_EMPLOYEE_FAILURE",

  ADMIN_UPDATE_EMPLOYEE_REQUEST: "ADMIN_UPDATE_EMPLOYEE_REQUEST",
  ADMIN_UPDATE_EMPLOYEE_SUCCESS: "ADMIN_UPDATE_EMPLOYEE_SUCCESS",
  ADMIN_UPDATE_EMPLOYEE_FAILURE: "ADMIN_UPDATE_EMPLOYEE_FAILURE",

  ADMIN_UPDATE_USER_REQUEST: "ADMIN_UPDATE_USER_REQUEST",
  ADMIN_UPDATE_USER_SUCCESS: "ADMIN_UPDATE_USER_SUCCESS",
  ADMIN_UPDATE_USER_FAILURE: "ADMIN_UPDATE_USER_FAILURE",

  ADMIN_LOAD_FEEDBACK_REQUEST: "ADMIN_LOAD_FEEDBACK_REQUEST",
  ADMIN_LOAD_FEEDBACK_SUCCESS: "ADMIN_LOAD_FEEDBACK_SUCCESS",
  ADMIN_LOAD_FEEDBACK_FAILURE: "ADMIN_LOAD_FEEDBACK_FAILURE"
};
